### ISSUE TITLE
🧹 4.0 cleanups

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#4171]
This is a list of changes that we can't do right now but should do in the next major release. This list is mostly a braindump and is missing a lot of context. **This is not about new features but rather a list of small cleanups to do**.

If you see anything that doesn't make any sense, it's probably because it doesn't. Feel free to comment and we'll dive into it.

### Potential Breaking Changes/cleanups

* [x] ~Remove `suspend` from the `ApolloStore` APIs~ Offer a non-suspend version
* [x] Validation of operation directives #4518
* [x] Switch jvm-defaults to "all" (thus requiring Java8, which we require already anyways)
* [x] Remove antlr
* [x] move deferredMergedFragments and variables outside of `CustomScalarAdapter`
* [x] Make apollo-ast's `com.apollographql.apollo3.ast.introspection.*` classes non public to reduce the API surface (including the json serializers) as they are probably not useful to end-users
* [x] Enable KDoc again
* [x] Add schemaPackageName/packageName to the Gradle configuration.
* [x] [ApolloCall execute / toFlow / exception handling improvements](https://github.com/apollographql/apollo-kotlin/issues/4003) 
* [x] introduce `HasDirective` interface
* [x] [Rename `dispose` to `close` and implement `okio.Closeable` on `NetworkTransport`, `HttpEngine`, `ApolloStore`](https://github.com/apollographql/apollo-kotlin/issues/4150) - That makes it difficult as it is a breaking change to add methods on interfaces. 
* [x] Remove `Fragment.readDataFromCache`
* [x] Capitalize the generated class name for enums, to be consistent with other generated types
* [x] Validate operation directives https://github.com/apollographql/apollo-kotlin/issues/2673
* [x] [Deprecate ApolloCompositeException with Error level and use suppressed exceptions instead](https://github.com/apollographql/apollo-kotlin/issues/4062)
* [x] ~Make `ApolloMetadata` internal~ (it's ultimately not internal because needed by plugins)
* [ ] Enforce opt-in the `kotlin_labs` linking
* [ ] [Rename `Foo.type` to `Foo.__type` to avoid nameclashes](https://github.com/apollographql/apollo-kotlin/pull/4144#issuecomment-1141109867) (or just leave it like this because we can detect the case. See https://github.com/apollographql/apollo-kotlin/issues/4293)
* [ ] Rewrite the buffered adapters to not use JsonReader anymore
* [ ] Cleanup the `JsonReader` API and distinguish between the buffer/non buffered case. 
* [ ] Generate the customScalarAdapters?
* [ ] Make the field merging validation more strict (see https://github.com/apollographql/apollo-kotlin/pull/4342#pullrequestreview-1083903524)
* [ ] Use scalar instead of customScalar https://github.com/apollographql/apollo-kotlin/issues/3815
* [ ] Refactor `shapes()` 
* [ ] Move httpInfo and others outside of executionContext
* [ ] Improve the Java ergonomics of `HttpKt`
* [ ] (To be considered): pass the variant name to the lambda for `createAllAndroidVariantServices` (see [this comment](https://github.com/apollographql/apollo-kotlin/issues/4490#issuecomment-1303256930)) (or deprecate the function?)
* [ ] [Rename `WsProtocol.Factory` to `WsProtocol.Builder`](https://github.com/apollographql/apollo-kotlin/pull/4589/files#r1050794657)
* [ ] Remove IdlingResource. See [this comment](https://github.com/JakeWharton/okhttp-idling-resource/issues/23#issuecomment-1353225191) from OkHttp for instance, and [this article](https://medium.com/androiddevelopers/alternatives-to-idling-resources-in-compose-tests-8ae71f9fc473) about how to avoid them with Compose.
* [ ] Remove circular dependencies between Gradle projects
* [ ] extract HttpEngine and WebSocketEngine to a common module
* [x] Remove our own `runTest`
* [ ] Remove Gradle defaultService

**Comment by eduardb** [comment]
Just saw this, and "Remove `Fragment.readDataFromCache`" from the list grabbed my attention. Would this also imply removing `ApolloStore.readFragment()`? I am interested in this because our app relies heavily on being able to query for fragments from the store (and watch them, but that's its own can of worms 😁). Thanks!

**Comment by martinbonnin** [comment]
It's a technicality mostly. `Fragment.readDataFromCache` will be removed but all the functionality will be exposed as `Executable.readDataFromCache`. If you take a look at [the source](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-normalized-cache-api-incubating/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/OperationCacheExtensions.kt#L74), both of them are present already, but one is deprecated because not really needed.
AFAIK, it should be source compatible so you shouldn't need to change anything.

**Comment by dsvensson** [comment]
Is there any target date for when 4.0 is to be released?

**Comment by BoD** [comment]
@dsvensson Our current target [is this month](https://github.com/apollographql/apollo-kotlin/blob/main/ROADMAP.md). We recommend you start looking at the latest beta if you haven't done so yet, feedback is super appreciated!

**Comment by bignimbus** [comment]
As we are in the RC stage for 4.0, we're going to close this and open a different Issue with just the "unchecked" items 🚀
