### ISSUE TITLE
[Umbrella issue] Better Java support in Apollo Kotlin

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#4283]
Apollo Kotlin 3 is focused at Kotlin and the changes to make it easier to consume in Kotlin had some unfortunate side effects for Java consumers. This issue is a place to list all the changes required to make it easier to consume Apollo Kotlin from Java projects.

The plan is to decouple Apollo Java so that it’s built on top of `apollo-api `but can evolve separate from Apollo Kotlin. In particular, Apollo Java will go through an alpha-beta-release phase. 

Current plan:

alpha.1

* [x] #4388
* [x] #4389
* [x] #4430
* [x] #4429
* [x] #4392
* [x] #4390 
* [x] #4391 
* [ ] #4394 
* [x] #4393 
* [ ] #4396 
* [ ] #4395 
* [x] #4337
* [x] https://github.com/apollographql/apollo-kotlin/issues/4213
* [x] #4398
* [x] #4417
* [x] #4399
* [x] Add builders for operations: https://github.com/apollographql/apollo-kotlin/issues/4312
* [x] Add builders for response data: https://github.com/apollographql/apollo-kotlin/issues/4016
* [ ] #4110

beta.1

* [x] #4397

**Comment by jpvajda** [comment]
@martinbonnin  👋  This seems like a good candidate for a 3.7 release, I went ahead and added all the issues to that release. I know you mentioned you had some more work to break down. Just let me know if this is the right release to targer this in, as it's our next release.

**Comment by martinbonnin** [comment]
We'll need certainly need a round of alpha/beta/rc releases on the Java Runtime. The API surface is huge and while we know where we're going (it's a translation of the Kotlin runtime, features are known already), fine tuning the APIs and getting community feedback will take time.

A good initial could be to ship a `apollo-runtime-java` artifact that allows to do a minimal query. Then we can build on top of it until it is feature complete:
- normalized cache
- http cache
- APQ
- batching
- uploads
- websockets
- more...

**Comment by jpvajda** [comment]
👋  Anyone who'd like to participate in a survey to help us better understand the need for better Java Support can find that survey here: https://github.com/apollographql/apollo-kotlin/issues/4501

**Comment by bignimbus** [comment]
Copypasta from a related issue:

We think that our experimental Java support is feature-complete for the 4.0.0 release, the remaining tasks have not yet been prioritized. We'll keep them open but in the interest of keeping our task list clean we'll close this umbrella Issue.

**Comment by aarmistead-chwy** [comment]
Is there a way to generate getter methods now?
currently having to drop back from doing something like `.map(ApolloResponse::errors)` to `.map(r -> r.errors)`

**Comment by BoD** [comment]
@aarmistead-chwy Sorry for the late reply - there is no option to generate getters. We do have an example to achieve this via a [compiler plugin](https://www.apollographql.com/docs/kotlin/v4/advanced/compiler-plugins) (in v4), [here](https://github.com/apollographql/apollo-kotlin/blob/main/tests/compiler-plugins/getters-and-setters/src/main/kotlin/hooks/TestPlugin.kt).
