### ISSUE TITLE
[Umbrella issue] modernize build system

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#4325]
* [x] switch to version catalog
* [x] https://github.com/apollographql/apollo-kotlin/issues/3531
* [x] #4335
* [x] enable build cache
* [ ] #4416

**Comment by martinbonnin** [comment]
Closing in favor of https://github.com/apollographql/apollo-kotlin/issues/4416
Note we can monitor our build system at ge.apollographql.com
