### ISSUE TITLE
[IJ/AS plugin] Initial release umbrella ticket

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-kotlin#4619]
This ticket keeps track of the necessary tasks for an initial release of a AS/IJ plugin:

```[tasklist]
### Initial release
- [x] https://github.com/apollographql/apollo-kotlin/issues/4620
- [x] https://github.com/apollographql/apollo-kotlin/issues/4621
- [x] Migration helpers v2 → v3
- [ ] https://github.com/apollographql/apollo-kotlin/issues/4622
- [x] https://github.com/apollographql/apollo-kotlin/issues/4624
- [x] https://github.com/apollographql/apollo-kotlin/issues/4625
- [x] https://github.com/apollographql/apollo-kotlin/issues/4760
- [ ] https://github.com/apollographql/apollo-kotlin/issues/4761
- [x] https://github.com/apollographql/apollo-kotlin/issues/4759
- [ ] https://github.com/apollographql/apollo-kotlin/issues/4889
- [ ] https://github.com/apollographql/apollo-kotlin/issues/4919
- [ ] https://github.com/apollographql/apollo-kotlin/issues/4942
- [ ] https://github.com/apollographql/apollo-kotlin/issues/5052
```
