### ISSUE TITLE
Megaissue: improvements to WebSockets

### ISSUE THREAD

**Issue by bignimbus** [apollographql/apollo-kotlin#5648]
```[tasklist]
### Tasks
- [ ] https://github.com/apollographql/apollo-kotlin/issues/2765
- [ ] https://github.com/apollographql/apollo-kotlin/issues/3020
- [ ] https://github.com/apollographql/apollo-kotlin/issues/4652
- [ ] https://github.com/apollographql/apollo-kotlin/issues/5217
```

**Comment by martinbonnin** [comment]
Closing as WebSocketNetworkTransport is shipped as part of `4.0.0-beta.6`. 
See https://github.com/apollographql/apollo-kotlin/issues/5862 for follow ups.
