### ISSUE TITLE
Cleanups

### ISSUE THREAD

**Issue by bignimbus** [apollographql/apollo-kotlin#6078]
This is a list of changes that we don't want to forget about.  They are likely to be backwards-incompatible so most of these will need to wait for a future major release. This list is mostly a braindump and is missing a lot of context. **This is not about new features but rather a list of small cleanups to do**.

Continued from https://github.com/apollographql/apollo-kotlin/issues/4171

If you see anything that doesn't make any sense, it's probably because it doesn't. Feel free to comment and we'll dive into it.

### Potential Breaking Changes/cleanups

* [ ] Enforce opt-in the `kotlin_labs` linking
* [ ] [Rename `Foo.type` to `Foo.__type` to avoid nameclashes](https://github.com/apollographql/apollo-kotlin/pull/4144#issuecomment-1141109867) (or just leave it like this because we can detect the case. See https://github.com/apollographql/apollo-kotlin/issues/4293)
* [ ] Rewrite the buffered adapters to not use JsonReader anymore
* [ ] Cleanup the `JsonReader` API and distinguish between the buffer/non buffered case. 
* [ ] Generate the customScalarAdapters?
* [ ] Make the field merging validation more strict (see https://github.com/apollographql/apollo-kotlin/pull/4342#pullrequestreview-1083903524)
* [ ] Use scalar instead of customScalar https://github.com/apollographql/apollo-kotlin/issues/3815
* [ ] Refactor `shapes()` 
* [ ] Move httpInfo and others outside of executionContext
* [ ] Improve the Java ergonomics of `HttpKt`
* [ ] (To be considered): pass the variant name to the lambda for `createAllAndroidVariantServices` (see [this comment](https://github.com/apollographql/apollo-kotlin/issues/4490#issuecomment-1303256930)) (or deprecate the function?)
* [ ] [Rename `WsProtocol.Factory` to `WsProtocol.Builder`](https://github.com/apollographql/apollo-kotlin/pull/4589/files#r1050794657)
* [ ] Remove IdlingResource. See [this comment](https://github.com/JakeWharton/okhttp-idling-resource/issues/23#issuecomment-1353225191) from OkHttp for instance, and [this article](https://medium.com/androiddevelopers/alternatives-to-idling-resources-in-compose-tests-8ae71f9fc473) about how to avoid them with Compose.
* [ ] Remove circular dependencies between Gradle projects
* [ ] extract HttpEngine and WebSocketEngine to a common module
* [ ] Remove Gradle defaultService

**Comment by gregjotau** [comment]
The engine extraction item would help us at ReAI: a Kotlin/Spring Boot JVM backend using Apollo for ten Shopify queries/mutations, with no subscriptions or normalized cache. We want to retain `ApolloClient` and its generated parsing while reusing our existing Spring/JDK HTTP stack.

In 5.1.0, OkHttp adds about **848 KiB** to our distribution. Providing a custom `HttpEngine` does not remove the dependency, and excluding OkHttp currently fails during client construction with `NoClassDefFoundError: okhttp3/WebSocket$Factory`: [`ApolloClient` eagerly builds the unused default WebSocket transport](https://github.com/apollographql/apollo-kotlin/blob/v5.1.0/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo/ApolloClient.kt#L154-L188). [PR #7018](https://github.com/apollographql/apollo-kotlin/pull/7018) defers that initialization so HTTP-only consumers with a custom engine can exclude it, with a regression test running without OkHttp on the JVM classpath.

Longer term, optional engine artifacts would make this cleaner. We'd welcome a documented breaking migration if necessary, with critical/security fixes maintained on an older release line. [OpenJDK's tip-and-tail model (JEP 14)](https://openjdk.org/jeps/14) seems relevant: evolve the tip while keeping tails focused on critical fixes. That would let consumers adopt a smaller, more modular runtime without asking stability-focused users to migrate immediately.
